### ISSUE TITLE
high-level pep517 deprecated

### ISSUE THREAD

**Issue by AstraLuma** [duckinator/ruff#1]
per https://github.com/pypa/pep517/blob/main/README.rst#deprecated-high-level

**Comment by duckinator** [comment]
The good news is, using `build` (like bork does), this will probably actually simplify the codebase.

Here's what Bork does atm for building sdist + bdist:

```python
import build

def dist():
    """Build the sdist and wheel distributions."""

    builder = build.ProjectBuilder('.')
    builder.build('sdist', './dist/')
    builder.build('wheel', './dist/')
```
